### ISSUE TITLE
Readme instructions

### ISSUE THREAD

**Issue by mgwidmann** [chrismccord/dot_emacs#4]
Sorry to open an issue here, but I was trying this setup as a fresh install of emacs and can't seem to figure out whats wrong.

After running the instructions in the readme I get the following output:

![screen shot 2015-12-21 at 9 49 31 pm](https://cloud.githubusercontent.com/assets/5035724/11946826/c8b27846-a82c-11e5-93d0-46b908f711e7.png)

From googling around it looks like I don't have some plugins installed maybe, like `el-get`?

I'd like to get into emacs/vim but the learning curve and issues like this always push back... :disappointed:

**Comment by chrismccord** [comment]
Did you install `cask` and run `cask install` in your `~/.emacs.d/` directory? What emacs version?

> I'd like to get into emacs/vim but the learning curve and issues like this always push back...

It's a sunk cost initially, but I promise it is worth if it you stick it out :)

**Comment by mgwidmann** [comment]
yep, did that :disappointed:

**Comment by mgwidmann** [comment]
I'm on a different machine now, just ran the setup instructions again, heres what happened:

In the directory of an elixir app:

```
$ emacs .
```

This screen flashes:

<img width="1552" alt="screen shot 2015-12-22 at 1 43 31 pm" src="https://cloud.githubusercontent.com/assets/5035724/11963022/044e0fb6-a8b2-11e5-9467-f785e3561d83.png">

Then this screen shows up:

<img width="1552" alt="screen shot 2015-12-22 at 1 43 57 pm" src="https://cloud.githubusercontent.com/assets/5035724/11963026/112852f0-a8b2-11e5-8332-91b990e58236.png">

Running with `--debug-init` like it suggests gives the following output:

```
-uuu:---F1  *scratch*      All L1     [(Fundamental)]-----------------------------------------------------------------------------
Debugger entered--Lisp error: (file-error "Cannot open load file" "package")
  require(package)
  eval-buffer(#<buffer  *load*> nil "/Users/mattwidmann/.emacs.d/init.el" nil t)  ; Reading at buffer position 19
  load-with-code-conversion("/Users/mattwidmann/.emacs.d/init.el" "/Users/mattwidmann/.emacs.d/init.el" t t)
  load("/Users/mattwidmann/.emacs.d/init" t t)
  #[nil "^H\205\276^@   \306=\203^Q^@\307^H\310Q\202A^@ \311=\2033^@\312\307\313\314#\203#^@\315\202A^@\312\307\313\316#\203/^@\3$
  command-line()
  normal-top-level()
```

:confounded:

**Comment by mgwidmann** [comment]
Realized I didn't mention the emacs version, both machines I've tried this on were fresh installs with `brew`...

```
$ emacs --version                                                                                                    ‹ruby-2.2.3›
GNU Emacs 22.1.1
Copyright (C) 2007 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

**Comment by chrismccord** [comment]
Your emacs version is the issue:

```
$ emacs --version
GNU Emacs 24.5.1
```

Run `brew update && brew upgrade emacs` then retry!

**Comment by mgwidmann** [comment]
:disappointed: still no luck

So I found out that my version of cask was slightly behind (0.7.2 vs 0.7.4) so I've updated to that. But I see a problem in the `init.el` script, it attempts to load file `/usr/local/share/emacs/site-lisp/cask.el` but the output from `brew install cask` shows that its been installed to a different location:

```
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/cask
```

Making the path instead become `/usr/local/share/emacs/site-lisp/cask/cask.el`.

After that I've moved onto a different error now:
(I was starting it up using oh-my-zsh, and I suspect that was a problem for some reason)

```
bash-3.2$ emacs . --debug-init
Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" "~/.emacs.d/vendor/osx-clipboard-mode/osx-clipboard.el")
```

When I visit that file is not there, just the folder for `osx-clipboard-mode` with nothing in it.

`cask install` produces no output (I'm assuming since everything is installed).

Any ideas?

**Comment by chrismccord** [comment]
> When I visit that file is not there, just the folder for osx-clipboard-mode with nothing in it.

Bah sorry you are nearly there! This last error is my fault, I hacked the sox-clipboard-mode to get around an el capitan issue and forgot to update my cask file. Please pull from master and all should be well!

**Comment by mgwidmann** [comment]
I think things are working now!

No errors and it seems to be all working... Now I just need to learn to use this thing :laughing:
